# Generated by Django 2.2.5 on 2019-09-17 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('patient_code', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('insurance_id', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField()),
                ('home_address', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('home_number', models.CharField(max_length=20)),
                ('work_number', models.CharField(max_length=20)),
                ('allergies', models.TextField(max_length=200)),
                ('chronic_diseases', models.TextField(max_length=200)),
                ('other_medical_info', models.TextField(max_length=200)),
                ('hospital', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Hospital', verbose_name='Hospital')),
            ],
        ),
    ]
