# Generated by Django 2.2.5 on 2019-09-17 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190917_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
