# Generated by Django 2.2.5 on 2019-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190917_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='allergies',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='birthday',
            field=models.DateField(default='2000-1-20'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='chronic_diseases',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='home_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='other_medical_info',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='work_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
